singleuser:
  cmd:
    - jupyterhub-singleuser
    - --notebook-dir=/home/jovyan
    - --allow-root
    - --NotebookApp.token=''
    - --NotebookApp.password=''
    - --NotebookApp.allow_origin='*'
  defaultUrl: "/lab"
  extraEnv:
    JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
  image:
    # You should replace the "latest" tag with a fixed version from:
    # https://hub.docker.com/r/jupyter/datascience-notebook/tags/
    # Inspect the Dockerfile at:
    # https://github.com/jupyter/docker-stacks/tree/HEAD/datascience-notebook/Dockerfile
    name: jupyter/datascience-notebook
    tag: latest