apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocker-tidyverse.fullname" . }}
  labels:
    {{- include "rocker-tidyverse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "rocker-tidyverse.selectorLabels" . | nindent 4 }}
